apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname.name }}-config
  namespace: {{ .Values.appname.appns }}
data:
  LOCAL_DB: {{ .Values.config.localDb | quote }}
  MYSQL_HOST: {{ .Values.config.mysqlHost | quote }}
  MYSQL_PORT: {{ .Values.config.mysqlPort | quote }}
  MYSQL_DB: {{ .Values.config.mysqlDb | quote }}
  MYSQL_PARAMS: {{ .Values.config.mysqlParams | quote }}
