apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname.name }}-service
  namespace: {{ .Values.appname.appns }}
spec:
  selector:
    app: {{ .Values.appname.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
