apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/dhananjayksharma/golang-k8s-microservices.git
    targetRevision: main
    path: payment-service-deployment/section-hpa-k8s
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: payment-service-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true