apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-service
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/REPLACE_ME/golang-k8s-microservices.git
    targetRevision: main
    path: message-service/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
