apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/REPLACE_ME/golang-k8s-microservices.git
    targetRevision: main
    path: payment-service-deployment/section-hpa-k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
