apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname.name }}-secret
  namespace: {{ .Values.appname.paymentservicens }}
type: Opaque
stringData:
  MYSQL_USER: {{ required "Set secrets.mysqlUser via --set-string or values-secret.yaml" .Values.secrets.mysqlUser | quote }}
  MYSQL_PASSWORD: {{ required "Set secrets.mysqlPassword via --set-string or values-secret.yaml" .Values.secrets.mysqlPassword | quote }}
