// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"github.com/gin-gonic/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ResponseKind.
const (
	ResponseKindError        ResponseKind = "error"
	ResponseKindStandard     ResponseKind = "standard"
	ResponseKindVerifySource ResponseKind = "verify_source"
)

// Valid indicates whether the value is a known member of the ResponseKind enum.
func (e ResponseKind) Valid() bool {
	switch e {
	case ResponseKindError:
		return true
	case ResponseKindStandard:
		return true
	case ResponseKindVerifySource:
		return true
	default:
		return false
	}
}

// APIResponse defines model for APIResponse.
type APIResponse struct {
	Data         interface{}   `json:"data,omitempty"`
	Error        *ErrorDetail  `json:"error,omitempty"`
	Kind         ResponseKind  `json:"kind"`
	Meta         *ResponseMeta `json:"meta,omitempty"`
	VerifySource *VerifySource `json:"verify_source,omitempty"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Code Example: INVALID_REQUEST
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Example: Request validation failed
	Message string `json:"message"`
}

// ResponseKind defines model for ResponseKind.
type ResponseKind string

// ResponseMeta defines model for ResponseMeta.
type ResponseMeta struct {
	Count     *int                `json:"count,omitempty"`
	Limit     *int                `json:"limit,omitempty"`
	Offset    *int                `json:"offset,omitempty"`
	RequestId *openapi_types.UUID `json:"request_id,omitempty"`
}

// VerifySource defines model for VerifySource.
type VerifySource struct {
	Source   string `json:"source"`
	Verified bool   `json:"verified"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {

}
